In [14]:
import math
import numpy as np

In [15]:
def gradient(parameters):
    x, y, z = parameters
    return np.array([6* ((x+3*y-z)**2) + 6, 18 * ((x + 3*y - z)**2), -6 * ((x + 3*y - z)**2)])

In [20]:
parameters = np.array([-2, 2, 3])
step_size = 1/6
for i in range(2):
    print(gradient(parameters))
    print(step_size )
    parameters = parameters -  step_size * gradient(parameters)
    print(parameters)

[12 18 -6]
[-4. -1.  4.]
[ 732. 2178. -726.]
[-126. -364.  125.]


In [17]:
a, b = np.array([1, 2])

In [10]:
a

1

In [11]:
b

2